import 'dart:developer';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/foundation.dart';
import 'package:fover/main.dart';
import 'package:fover/src/services/copyparty_service.dart';
import 'package:fover/src/services/photo_store.dart';
import 'package:fover/src/utils/common_utils.dart';
import 'package:path_provider/path_provider.dart';
import 'package:http/http.dart' as http;

// Notice sur l'IA : Ce code a été généré par Claude Sonnet 4.6
// AI notice: This code was generated by Claude Sonnet 4.6.

class DownloadService {
  static Future<String?> download({
    required String encodedPath,
    required String filename,
    void Function(int received, int total)? onProgress,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final downloadsDir = Directory('${dir.path}/downloads');
    if (!downloadsDir.existsSync()) downloadsDir.createSync();

    final localPath = '${downloadsDir.path}/$filename';

    if (File(localPath).existsSync()) {
      await PhotoStore.update(path: encodedPath, localPath: localPath);
      return localPath;
    }

    if (detectBackend() == ServerBackend.freebox) {
      final response = await client?.fetch(
        url: "v15/dl/$encodedPath",
        parseJson: false,
      );


      if (response?.data is !Uint8List) return null;

      final bytes = response!.data as Uint8List;
      await File(localPath).writeAsBytes(bytes);
    } else {
      final url = "${CopypartyService.baseUrl}/photos/$encodedPath";
      final response = await http.get(Uri.parse(url), headers: {
        'Authorization': 'Basic ${CopypartyService.credentials}',
      });
      if (response.statusCode != 200) return null;
      final bytes = response.bodyBytes;
      await File(localPath).writeAsBytes(bytes);
      
    }

    await PhotoStore.update(path: encodedPath, localPath: localPath);

    log("ici");

    return localPath;
  }

  static bool isDownloaded(String encodedPath) {
    final localPath = PhotoStore.get(encodedPath)?.localPath;
    return localPath != null && File(localPath).existsSync();
  }

  static Future<void> remove(String encodedPath) async {
    final photo = PhotoStore.get(encodedPath);
    if (photo?.localPath != null) {
      await File(photo!.localPath!).delete();
      await PhotoStore.update(path: encodedPath, localPath: null);
    }
  }
}
