import 'dart:developer';
import 'dart:io';
import 'dart:typed_data';
import 'package:fover/main.dart';
import 'package:fover/src/services/photo_store.dart';
import 'package:path_provider/path_provider.dart';

// Notice sur l'IA : Ce code a été généré par Claude Sonnet 4.6
// AI notice: This code was generated by Claude Sonnet 4.6.

class DownloadService {
  static Future<String?> download({
    required String encodedPath,
    required String filename,
    void Function(int received, int total)? onProgress,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final downloadsDir = Directory('${dir.path}/downloads');
    if (!downloadsDir.existsSync()) downloadsDir.createSync();

    final localPath = '${downloadsDir.path}/$filename';

    if (File(localPath).existsSync()) return localPath;
    final response = await client?.fetch(
      url: "v15/dl/$encodedPath",
      parseJson: false,
    );

    if (response?.data is !Uint8List) return null;

    final bytes = response!.data as Uint8List;
    await File(localPath).writeAsBytes(bytes);

    await PhotoStore.update(path: encodedPath, localPath: localPath);

    log("ici");

    return localPath;
  }

  static bool isDownloaded(String encodedPath) {
    final localPath = PhotoStore.get(encodedPath)?.localPath;
    return localPath != null && File(localPath).existsSync();
  }

  static Future<void> remove(String encodedPath) async {
    final photo = PhotoStore.get(encodedPath);
    if (photo?.localPath != null) {
      await File(photo!.localPath!).delete();
      await PhotoStore.update(path: encodedPath, localPath: null);
    }
  }
}
