// Notice sur l'IA : Ce code a été généré par Claude Sonnet 4.6
// AI notice: This code was generated by Claude Sonnet 4.6

import UIKit
import Flutter
import AVFoundation

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    GeneratedPluginRegistrant.register(with: self)

    guard let controller = window?.rootViewController as? FlutterViewController else {
      fatalError("rootViewController is not type FlutterViewController")
    }

    let channel = FlutterMethodChannel(
      name: "fover/video_thumbnail",
      binaryMessenger: controller.binaryMessenger
    )

    channel.setMethodCallHandler { call, result in
      if call.method == "getFirstFrame",
         let args = call.arguments as? [String: Any],
         let path = args["path"] as? String {

        let asset = AVAsset(url: URL(fileURLWithPath: path))
        let generator = AVAssetImageGenerator(asset: asset)
        generator.appliesPreferredTrackTransform = true
        generator.maximumSize = CGSize(width: 300, height: 300)

        do {
          let cgImage = try generator.copyCGImage(at: .zero, actualTime: nil)
          let uiImage = UIImage(cgImage: cgImage)
          print("cgImage: \(String(describing: cgImage))")
          if let jpegData = uiImage.jpegData(compressionQuality: 0.5) {
            result(FlutterStandardTypedData(bytes: jpegData))
          } else {
            result(FlutterError(code: "ENCODE_ERROR", message: nil, details: nil))
          }
        } catch {
          result(FlutterError(code: "FRAME_ERROR", message: error.localizedDescription, details: nil))
          print("AVFoundation error: \(error)")
        }

      } else {
        result(FlutterMethodNotImplemented)
      }
    }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
