// Notice sur l'IA : Ce code a été généré par Claude Sonnet 4.6
// AI notice: This code was generated by Claude Sonnet 4.6

import UIKit
import Flutter
import AVFoundation
import MapKit
import CoreLocation


@main
@objc class AppDelegate: FlutterAppDelegate {

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    GeneratedPluginRegistrant.register(with: self)

    guard let controller = window?.rootViewController as? FlutterViewController else {
      fatalError("rootViewController is not type FlutterViewController")
    }

    // ── Canal MapKit / MKLocalSearch ──────────────────────────────
    let mapChannel = FlutterMethodChannel(
      name: "com.fover/mapsearch",
      binaryMessenger: controller.binaryMessenger
    )

    mapChannel.setMethodCallHandler { call, result in
      guard call.method == "searchAddress" else {
        result(FlutterMethodNotImplemented)
        return
      }
      guard let query = call.arguments as? String else {
        result(FlutterError(code: "INVALID_ARGS", message: "Query manquant", details: nil))
        return
      }
      let request = MKLocalSearch.Request()
      request.naturalLanguageQuery = query
      request.region = MKCoordinateRegion(
        center: CLLocationCoordinate2D(latitude: 0, longitude: 0),
        span: MKCoordinateSpan(latitudeDelta: 180, longitudeDelta: 360)
      )
      // Chercher uniquement des adresses et points d'intérêt
      request.resultTypes = [.address, .pointOfInterest]

      MKLocalSearch(request: request).start { response, _ in
        guard let items = response?.mapItems else { result([]); return }
        let suggestions: [[String: Any]] = items.prefix(8).map { item in
          [
            "name":    item.name ?? "",
            "address": item.placemark.title ?? "",
            "lat":     item.placemark.coordinate.latitude,
            "lon":     item.placemark.coordinate.longitude,
          ]
        }
        result(suggestions)
      }
    }

    // ── Canal vidéo / AVFoundation ────────────────────────────────
    let videoChannel = FlutterMethodChannel(
      name: "fover/video_thumbnail",
      binaryMessenger: controller.binaryMessenger
    )

    videoChannel.setMethodCallHandler { call, result in
      if call.method == "getFirstFrame",
         let args = call.arguments as? [String: Any],
         let path = args["path"] as? String {

        let asset = AVAsset(url: URL(fileURLWithPath: path))
        let generator = AVAssetImageGenerator(asset: asset)
        generator.appliesPreferredTrackTransform = true
        generator.maximumSize = CGSize(width: 300, height: 300)

        do {
          let cgImage = try generator.copyCGImage(at: .zero, actualTime: nil)
          let uiImage = UIImage(cgImage: cgImage)
          if let jpegData = uiImage.jpegData(compressionQuality: 0.5) {
            result(FlutterStandardTypedData(bytes: jpegData))
          } else {
            result(FlutterError(code: "ENCODE_ERROR", message: "Encodage JPEG échoué", details: nil))
          }
        } catch {
          result(FlutterError(code: "FRAME_ERROR", message: error.localizedDescription, details: nil))
        }

      } else {
        result(FlutterMethodNotImplemented)
      }
    }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}